version: '3'
services:
  api:
    image: node:14
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
